#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPengajuanSkripsi
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="bimbingan_final")]
	public partial class dbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttb_thn_akademik(tb_thn_akademik instance);
    partial void Updatetb_thn_akademik(tb_thn_akademik instance);
    partial void Deletetb_thn_akademik(tb_thn_akademik instance);
    partial void Inserttb_bimbingan(tb_bimbingan instance);
    partial void Updatetb_bimbingan(tb_bimbingan instance);
    partial void Deletetb_bimbingan(tb_bimbingan instance);
    partial void Inserttb_dosen(tb_dosen instance);
    partial void Updatetb_dosen(tb_dosen instance);
    partial void Deletetb_dosen(tb_dosen instance);
    partial void Inserttb_fakulta(tb_fakulta instance);
    partial void Updatetb_fakulta(tb_fakulta instance);
    partial void Deletetb_fakulta(tb_fakulta instance);
    partial void Inserttb_jabatan(tb_jabatan instance);
    partial void Updatetb_jabatan(tb_jabatan instance);
    partial void Deletetb_jabatan(tb_jabatan instance);
    partial void Inserttb_jurusan(tb_jurusan instance);
    partial void Updatetb_jurusan(tb_jurusan instance);
    partial void Deletetb_jurusan(tb_jurusan instance);
    partial void Inserttb_kaprodi(tb_kaprodi instance);
    partial void Updatetb_kaprodi(tb_kaprodi instance);
    partial void Deletetb_kaprodi(tb_kaprodi instance);
    partial void Inserttb_mahasiswa(tb_mahasiswa instance);
    partial void Updatetb_mahasiswa(tb_mahasiswa instance);
    partial void Deletetb_mahasiswa(tb_mahasiswa instance);
    partial void Inserttb_peminatan(tb_peminatan instance);
    partial void Updatetb_peminatan(tb_peminatan instance);
    partial void Deletetb_peminatan(tb_peminatan instance);
    partial void Inserttb_proposal(tb_proposal instance);
    partial void Updatetb_proposal(tb_proposal instance);
    partial void Deletetb_proposal(tb_proposal instance);
    partial void Inserttb_room(tb_room instance);
    partial void Updatetb_room(tb_room instance);
    partial void Deletetb_room(tb_room instance);
    partial void Inserttb_chat(tb_chat instance);
    partial void Updatetb_chat(tb_chat instance);
    partial void Deletetb_chat(tb_chat instance);
    #endregion
		
		public dbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["bimbingan_onlineConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<v_chat> v_chats
		{
			get
			{
				return this.GetTable<v_chat>();
			}
		}
		
		public System.Data.Linq.Table<v_room> v_rooms
		{
			get
			{
				return this.GetTable<v_room>();
			}
		}
		
		public System.Data.Linq.Table<v_peminatan> v_peminatans
		{
			get
			{
				return this.GetTable<v_peminatan>();
			}
		}
		
		public System.Data.Linq.Table<v_proposal> v_proposals
		{
			get
			{
				return this.GetTable<v_proposal>();
			}
		}
		
		public System.Data.Linq.Table<tb_thn_akademik> tb_thn_akademiks
		{
			get
			{
				return this.GetTable<tb_thn_akademik>();
			}
		}
		
		public System.Data.Linq.Table<tb_bimbingan> tb_bimbingans
		{
			get
			{
				return this.GetTable<tb_bimbingan>();
			}
		}
		
		public System.Data.Linq.Table<tb_dosen> tb_dosens
		{
			get
			{
				return this.GetTable<tb_dosen>();
			}
		}
		
		public System.Data.Linq.Table<tb_fakulta> tb_fakultas
		{
			get
			{
				return this.GetTable<tb_fakulta>();
			}
		}
		
		public System.Data.Linq.Table<tb_jabatan> tb_jabatans
		{
			get
			{
				return this.GetTable<tb_jabatan>();
			}
		}
		
		public System.Data.Linq.Table<tb_jurusan> tb_jurusans
		{
			get
			{
				return this.GetTable<tb_jurusan>();
			}
		}
		
		public System.Data.Linq.Table<tb_kaprodi> tb_kaprodis
		{
			get
			{
				return this.GetTable<tb_kaprodi>();
			}
		}
		
		public System.Data.Linq.Table<tb_mahasiswa> tb_mahasiswas
		{
			get
			{
				return this.GetTable<tb_mahasiswa>();
			}
		}
		
		public System.Data.Linq.Table<tb_peminatan> tb_peminatans
		{
			get
			{
				return this.GetTable<tb_peminatan>();
			}
		}
		
		public System.Data.Linq.Table<tb_proposal> tb_proposals
		{
			get
			{
				return this.GetTable<tb_proposal>();
			}
		}
		
		public System.Data.Linq.Table<tb_room> tb_rooms
		{
			get
			{
				return this.GetTable<tb_room>();
			}
		}
		
		public System.Data.Linq.Table<tb_chat> tb_chats
		{
			get
			{
				return this.GetTable<tb_chat>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_chat")]
	public partial class v_chat
	{
		
		private int _id_chat;
		
		private System.Nullable<int> _id_room;
		
		private string _isi;
		
		private string _nim;
		
		private string _nama_pengirim;
		
		private string _nid;
		
		private string _nama_penerima;
		
		public v_chat()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_chat", DbType="Int NOT NULL")]
		public int id_chat
		{
			get
			{
				return this._id_chat;
			}
			set
			{
				if ((this._id_chat != value))
				{
					this._id_chat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_room", DbType="Int")]
		public System.Nullable<int> id_room
		{
			get
			{
				return this._id_room;
			}
			set
			{
				if ((this._id_room != value))
				{
					this._id_room = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isi", DbType="VarChar(30)")]
		public string isi
		{
			get
			{
				return this._isi;
			}
			set
			{
				if ((this._isi != value))
				{
					this._isi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nim", DbType="VarChar(20)")]
		public string nim
		{
			get
			{
				return this._nim;
			}
			set
			{
				if ((this._nim != value))
				{
					this._nim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_pengirim", DbType="VarChar(50)")]
		public string nama_pengirim
		{
			get
			{
				return this._nama_pengirim;
			}
			set
			{
				if ((this._nama_pengirim != value))
				{
					this._nama_pengirim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nid", DbType="VarChar(20)")]
		public string nid
		{
			get
			{
				return this._nid;
			}
			set
			{
				if ((this._nid != value))
				{
					this._nid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_penerima", DbType="VarChar(50)")]
		public string nama_penerima
		{
			get
			{
				return this._nama_penerima;
			}
			set
			{
				if ((this._nama_penerima != value))
				{
					this._nama_penerima = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_room")]
	public partial class v_room
	{
		
		private int _id_room;
		
		private System.Nullable<int> _id_mahasiswa;
		
		private System.Nullable<int> _id_pembimbing;
		
		private System.Nullable<System.DateTime> _tgl_room;
		
		private System.Nullable<int> _id_proposal;
		
		private string _judul_skripsi;
		
		private string _nim;
		
		private string _nama;
		
		private System.Nullable<int> _id_jurusan;
		
		private System.Nullable<int> _id_pembimbing_1;
		
		private System.Nullable<int> _id_pembimbing_2;
		
		public v_room()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_room", DbType="Int NOT NULL")]
		public int id_room
		{
			get
			{
				return this._id_room;
			}
			set
			{
				if ((this._id_room != value))
				{
					this._id_room = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_mahasiswa", DbType="Int")]
		public System.Nullable<int> id_mahasiswa
		{
			get
			{
				return this._id_mahasiswa;
			}
			set
			{
				if ((this._id_mahasiswa != value))
				{
					this._id_mahasiswa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pembimbing", DbType="Int")]
		public System.Nullable<int> id_pembimbing
		{
			get
			{
				return this._id_pembimbing;
			}
			set
			{
				if ((this._id_pembimbing != value))
				{
					this._id_pembimbing = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgl_room", DbType="DateTime")]
		public System.Nullable<System.DateTime> tgl_room
		{
			get
			{
				return this._tgl_room;
			}
			set
			{
				if ((this._tgl_room != value))
				{
					this._tgl_room = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_proposal", DbType="Int")]
		public System.Nullable<int> id_proposal
		{
			get
			{
				return this._id_proposal;
			}
			set
			{
				if ((this._id_proposal != value))
				{
					this._id_proposal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_judul_skripsi", DbType="VarChar(100)")]
		public string judul_skripsi
		{
			get
			{
				return this._judul_skripsi;
			}
			set
			{
				if ((this._judul_skripsi != value))
				{
					this._judul_skripsi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nim", DbType="VarChar(20)")]
		public string nim
		{
			get
			{
				return this._nim;
			}
			set
			{
				if ((this._nim != value))
				{
					this._nim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="VarChar(50)")]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this._nama = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_jurusan", DbType="Int")]
		public System.Nullable<int> id_jurusan
		{
			get
			{
				return this._id_jurusan;
			}
			set
			{
				if ((this._id_jurusan != value))
				{
					this._id_jurusan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pembimbing_1", DbType="Int")]
		public System.Nullable<int> id_pembimbing_1
		{
			get
			{
				return this._id_pembimbing_1;
			}
			set
			{
				if ((this._id_pembimbing_1 != value))
				{
					this._id_pembimbing_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pembimbing_2", DbType="Int")]
		public System.Nullable<int> id_pembimbing_2
		{
			get
			{
				return this._id_pembimbing_2;
			}
			set
			{
				if ((this._id_pembimbing_2 != value))
				{
					this._id_pembimbing_2 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_peminatan")]
	public partial class v_peminatan
	{
		
		private int _id_peminatan;
		
		private string _nama_peminatan;
		
		private System.Nullable<int> _id_fakultas;
		
		private System.Nullable<int> _id_jurusan;
		
		private string _nama_fakultas;
		
		private string _nama_jurusan;
		
		public v_peminatan()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_peminatan", DbType="Int NOT NULL")]
		public int id_peminatan
		{
			get
			{
				return this._id_peminatan;
			}
			set
			{
				if ((this._id_peminatan != value))
				{
					this._id_peminatan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_peminatan", DbType="VarChar(50)")]
		public string nama_peminatan
		{
			get
			{
				return this._nama_peminatan;
			}
			set
			{
				if ((this._nama_peminatan != value))
				{
					this._nama_peminatan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_fakultas", DbType="Int")]
		public System.Nullable<int> id_fakultas
		{
			get
			{
				return this._id_fakultas;
			}
			set
			{
				if ((this._id_fakultas != value))
				{
					this._id_fakultas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_jurusan", DbType="Int")]
		public System.Nullable<int> id_jurusan
		{
			get
			{
				return this._id_jurusan;
			}
			set
			{
				if ((this._id_jurusan != value))
				{
					this._id_jurusan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_fakultas", DbType="VarChar(50)")]
		public string nama_fakultas
		{
			get
			{
				return this._nama_fakultas;
			}
			set
			{
				if ((this._nama_fakultas != value))
				{
					this._nama_fakultas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_jurusan", DbType="VarChar(50)")]
		public string nama_jurusan
		{
			get
			{
				return this._nama_jurusan;
			}
			set
			{
				if ((this._nama_jurusan != value))
				{
					this._nama_jurusan = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_proposal")]
	public partial class v_proposal
	{
		
		private int _id_proposal;
		
		private System.Nullable<int> _id_mahasiswa;
		
		private System.Nullable<System.DateTime> _tgl_submit;
		
		private string _judul_skripsi;
		
		private System.Nullable<int> _id_pembimbing_1;
		
		private System.Nullable<int> _id_pembimbing_2;
		
		private string _status_proposal;
		
		private string _catatan_kaprodi;
		
		private System.Nullable<int> _id_kaprodi;
		
		private System.Nullable<int> _id_peminatan;
		
		private System.Nullable<int> _id_thn_akademik;
		
		private string _dosen_1;
		
		private string _dosen_2;
		
		private string _nama;
		
		private string _nim;
		
		private System.Nullable<int> _id_jurusan;
		
		private string _nama_peminatan;
		
		private string _nama_thn_akademik;
		
		public v_proposal()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_proposal", DbType="Int NOT NULL")]
		public int id_proposal
		{
			get
			{
				return this._id_proposal;
			}
			set
			{
				if ((this._id_proposal != value))
				{
					this._id_proposal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_mahasiswa", DbType="Int")]
		public System.Nullable<int> id_mahasiswa
		{
			get
			{
				return this._id_mahasiswa;
			}
			set
			{
				if ((this._id_mahasiswa != value))
				{
					this._id_mahasiswa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgl_submit", DbType="Date")]
		public System.Nullable<System.DateTime> tgl_submit
		{
			get
			{
				return this._tgl_submit;
			}
			set
			{
				if ((this._tgl_submit != value))
				{
					this._tgl_submit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_judul_skripsi", DbType="VarChar(100)")]
		public string judul_skripsi
		{
			get
			{
				return this._judul_skripsi;
			}
			set
			{
				if ((this._judul_skripsi != value))
				{
					this._judul_skripsi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pembimbing_1", DbType="Int")]
		public System.Nullable<int> id_pembimbing_1
		{
			get
			{
				return this._id_pembimbing_1;
			}
			set
			{
				if ((this._id_pembimbing_1 != value))
				{
					this._id_pembimbing_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pembimbing_2", DbType="Int")]
		public System.Nullable<int> id_pembimbing_2
		{
			get
			{
				return this._id_pembimbing_2;
			}
			set
			{
				if ((this._id_pembimbing_2 != value))
				{
					this._id_pembimbing_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_proposal", DbType="VarChar(100)")]
		public string status_proposal
		{
			get
			{
				return this._status_proposal;
			}
			set
			{
				if ((this._status_proposal != value))
				{
					this._status_proposal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_catatan_kaprodi", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string catatan_kaprodi
		{
			get
			{
				return this._catatan_kaprodi;
			}
			set
			{
				if ((this._catatan_kaprodi != value))
				{
					this._catatan_kaprodi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_kaprodi", DbType="Int")]
		public System.Nullable<int> id_kaprodi
		{
			get
			{
				return this._id_kaprodi;
			}
			set
			{
				if ((this._id_kaprodi != value))
				{
					this._id_kaprodi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_peminatan", DbType="Int")]
		public System.Nullable<int> id_peminatan
		{
			get
			{
				return this._id_peminatan;
			}
			set
			{
				if ((this._id_peminatan != value))
				{
					this._id_peminatan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_thn_akademik", DbType="Int")]
		public System.Nullable<int> id_thn_akademik
		{
			get
			{
				return this._id_thn_akademik;
			}
			set
			{
				if ((this._id_thn_akademik != value))
				{
					this._id_thn_akademik = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dosen_1", DbType="VarChar(50)")]
		public string dosen_1
		{
			get
			{
				return this._dosen_1;
			}
			set
			{
				if ((this._dosen_1 != value))
				{
					this._dosen_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dosen_2", DbType="VarChar(50)")]
		public string dosen_2
		{
			get
			{
				return this._dosen_2;
			}
			set
			{
				if ((this._dosen_2 != value))
				{
					this._dosen_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="VarChar(50)")]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this._nama = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nim", DbType="VarChar(20)")]
		public string nim
		{
			get
			{
				return this._nim;
			}
			set
			{
				if ((this._nim != value))
				{
					this._nim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_jurusan", DbType="Int")]
		public System.Nullable<int> id_jurusan
		{
			get
			{
				return this._id_jurusan;
			}
			set
			{
				if ((this._id_jurusan != value))
				{
					this._id_jurusan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_peminatan", DbType="VarChar(50)")]
		public string nama_peminatan
		{
			get
			{
				return this._nama_peminatan;
			}
			set
			{
				if ((this._nama_peminatan != value))
				{
					this._nama_peminatan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_thn_akademik", DbType="VarChar(50)")]
		public string nama_thn_akademik
		{
			get
			{
				return this._nama_thn_akademik;
			}
			set
			{
				if ((this._nama_thn_akademik != value))
				{
					this._nama_thn_akademik = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_thn_akademik")]
	public partial class tb_thn_akademik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_thn_akademik;
		
		private string _nama_thn_akademik;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_thn_akademikChanging(int value);
    partial void Onid_thn_akademikChanged();
    partial void Onnama_thn_akademikChanging(string value);
    partial void Onnama_thn_akademikChanged();
    #endregion
		
		public tb_thn_akademik()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_thn_akademik", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_thn_akademik
		{
			get
			{
				return this._id_thn_akademik;
			}
			set
			{
				if ((this._id_thn_akademik != value))
				{
					this.Onid_thn_akademikChanging(value);
					this.SendPropertyChanging();
					this._id_thn_akademik = value;
					this.SendPropertyChanged("id_thn_akademik");
					this.Onid_thn_akademikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_thn_akademik", DbType="VarChar(50)")]
		public string nama_thn_akademik
		{
			get
			{
				return this._nama_thn_akademik;
			}
			set
			{
				if ((this._nama_thn_akademik != value))
				{
					this.Onnama_thn_akademikChanging(value);
					this.SendPropertyChanging();
					this._nama_thn_akademik = value;
					this.SendPropertyChanged("nama_thn_akademik");
					this.Onnama_thn_akademikChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_bimbingan")]
	public partial class tb_bimbingan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_bimbingan;
		
		private string _file_bimbingan;
		
		private System.Nullable<System.DateTime> _tgl_upload;
		
		private System.Nullable<int> _id_room;
		
		private EntityRef<tb_room> _tb_room;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_bimbinganChanging(int value);
    partial void Onid_bimbinganChanged();
    partial void Onfile_bimbinganChanging(string value);
    partial void Onfile_bimbinganChanged();
    partial void Ontgl_uploadChanging(System.Nullable<System.DateTime> value);
    partial void Ontgl_uploadChanged();
    partial void Onid_roomChanging(System.Nullable<int> value);
    partial void Onid_roomChanged();
    #endregion
		
		public tb_bimbingan()
		{
			this._tb_room = default(EntityRef<tb_room>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_bimbingan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_bimbingan
		{
			get
			{
				return this._id_bimbingan;
			}
			set
			{
				if ((this._id_bimbingan != value))
				{
					this.Onid_bimbinganChanging(value);
					this.SendPropertyChanging();
					this._id_bimbingan = value;
					this.SendPropertyChanged("id_bimbingan");
					this.Onid_bimbinganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_bimbingan", DbType="VarChar(255)")]
		public string file_bimbingan
		{
			get
			{
				return this._file_bimbingan;
			}
			set
			{
				if ((this._file_bimbingan != value))
				{
					this.Onfile_bimbinganChanging(value);
					this.SendPropertyChanging();
					this._file_bimbingan = value;
					this.SendPropertyChanged("file_bimbingan");
					this.Onfile_bimbinganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgl_upload", DbType="Date")]
		public System.Nullable<System.DateTime> tgl_upload
		{
			get
			{
				return this._tgl_upload;
			}
			set
			{
				if ((this._tgl_upload != value))
				{
					this.Ontgl_uploadChanging(value);
					this.SendPropertyChanging();
					this._tgl_upload = value;
					this.SendPropertyChanged("tgl_upload");
					this.Ontgl_uploadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_room", DbType="Int")]
		public System.Nullable<int> id_room
		{
			get
			{
				return this._id_room;
			}
			set
			{
				if ((this._id_room != value))
				{
					if (this._tb_room.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_roomChanging(value);
					this.SendPropertyChanging();
					this._id_room = value;
					this.SendPropertyChanged("id_room");
					this.Onid_roomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_room_tb_bimbingan", Storage="_tb_room", ThisKey="id_room", OtherKey="id_room", IsForeignKey=true)]
		public tb_room tb_room
		{
			get
			{
				return this._tb_room.Entity;
			}
			set
			{
				tb_room previousValue = this._tb_room.Entity;
				if (((previousValue != value) 
							|| (this._tb_room.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_room.Entity = null;
						previousValue.tb_bimbingans.Remove(this);
					}
					this._tb_room.Entity = value;
					if ((value != null))
					{
						value.tb_bimbingans.Add(this);
						this._id_room = value.id_room;
					}
					else
					{
						this._id_room = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_room");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_dosen")]
	public partial class tb_dosen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_dosen;
		
		private string _nid;
		
		private string _nama;
		
		private System.Nullable<System.DateTime> _tgl_lahir;
		
		private System.Nullable<int> _id_jurusan;
		
		private System.Nullable<int> _id_fakultas;
		
		private System.Nullable<int> _id_jabatan;
		
		private string _pendidikan;
		
		private string _bidang_keahlian;
		
		private string _password;
		
		private EntitySet<tb_proposal> _tb_proposals;
		
		private EntitySet<tb_proposal> _tb_proposals1;
		
		private EntitySet<tb_room> _tb_rooms;
		
		private EntityRef<tb_fakulta> _tb_fakulta;
		
		private EntityRef<tb_jabatan> _tb_jabatan;
		
		private EntityRef<tb_jurusan> _tb_jurusan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_dosenChanging(int value);
    partial void Onid_dosenChanged();
    partial void OnnidChanging(string value);
    partial void OnnidChanged();
    partial void OnnamaChanging(string value);
    partial void OnnamaChanged();
    partial void Ontgl_lahirChanging(System.Nullable<System.DateTime> value);
    partial void Ontgl_lahirChanged();
    partial void Onid_jurusanChanging(System.Nullable<int> value);
    partial void Onid_jurusanChanged();
    partial void Onid_fakultasChanging(System.Nullable<int> value);
    partial void Onid_fakultasChanged();
    partial void Onid_jabatanChanging(System.Nullable<int> value);
    partial void Onid_jabatanChanged();
    partial void OnpendidikanChanging(string value);
    partial void OnpendidikanChanged();
    partial void Onbidang_keahlianChanging(string value);
    partial void Onbidang_keahlianChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
		
		public tb_dosen()
		{
			this._tb_proposals = new EntitySet<tb_proposal>(new Action<tb_proposal>(this.attach_tb_proposals), new Action<tb_proposal>(this.detach_tb_proposals));
			this._tb_proposals1 = new EntitySet<tb_proposal>(new Action<tb_proposal>(this.attach_tb_proposals1), new Action<tb_proposal>(this.detach_tb_proposals1));
			this._tb_rooms = new EntitySet<tb_room>(new Action<tb_room>(this.attach_tb_rooms), new Action<tb_room>(this.detach_tb_rooms));
			this._tb_fakulta = default(EntityRef<tb_fakulta>);
			this._tb_jabatan = default(EntityRef<tb_jabatan>);
			this._tb_jurusan = default(EntityRef<tb_jurusan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dosen", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_dosen
		{
			get
			{
				return this._id_dosen;
			}
			set
			{
				if ((this._id_dosen != value))
				{
					this.Onid_dosenChanging(value);
					this.SendPropertyChanging();
					this._id_dosen = value;
					this.SendPropertyChanged("id_dosen");
					this.Onid_dosenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nid", DbType="VarChar(20)")]
		public string nid
		{
			get
			{
				return this._nid;
			}
			set
			{
				if ((this._nid != value))
				{
					this.OnnidChanging(value);
					this.SendPropertyChanging();
					this._nid = value;
					this.SendPropertyChanged("nid");
					this.OnnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="VarChar(50)")]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this.OnnamaChanging(value);
					this.SendPropertyChanging();
					this._nama = value;
					this.SendPropertyChanged("nama");
					this.OnnamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgl_lahir", DbType="Date")]
		public System.Nullable<System.DateTime> tgl_lahir
		{
			get
			{
				return this._tgl_lahir;
			}
			set
			{
				if ((this._tgl_lahir != value))
				{
					this.Ontgl_lahirChanging(value);
					this.SendPropertyChanging();
					this._tgl_lahir = value;
					this.SendPropertyChanged("tgl_lahir");
					this.Ontgl_lahirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_jurusan", DbType="Int")]
		public System.Nullable<int> id_jurusan
		{
			get
			{
				return this._id_jurusan;
			}
			set
			{
				if ((this._id_jurusan != value))
				{
					if (this._tb_jurusan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_jurusanChanging(value);
					this.SendPropertyChanging();
					this._id_jurusan = value;
					this.SendPropertyChanged("id_jurusan");
					this.Onid_jurusanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_fakultas", DbType="Int")]
		public System.Nullable<int> id_fakultas
		{
			get
			{
				return this._id_fakultas;
			}
			set
			{
				if ((this._id_fakultas != value))
				{
					if (this._tb_fakulta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_fakultasChanging(value);
					this.SendPropertyChanging();
					this._id_fakultas = value;
					this.SendPropertyChanged("id_fakultas");
					this.Onid_fakultasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_jabatan", DbType="Int")]
		public System.Nullable<int> id_jabatan
		{
			get
			{
				return this._id_jabatan;
			}
			set
			{
				if ((this._id_jabatan != value))
				{
					if (this._tb_jabatan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_jabatanChanging(value);
					this.SendPropertyChanging();
					this._id_jabatan = value;
					this.SendPropertyChanged("id_jabatan");
					this.Onid_jabatanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pendidikan", DbType="VarChar(50)")]
		public string pendidikan
		{
			get
			{
				return this._pendidikan;
			}
			set
			{
				if ((this._pendidikan != value))
				{
					this.OnpendidikanChanging(value);
					this.SendPropertyChanging();
					this._pendidikan = value;
					this.SendPropertyChanged("pendidikan");
					this.OnpendidikanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bidang_keahlian", DbType="VarChar(255)")]
		public string bidang_keahlian
		{
			get
			{
				return this._bidang_keahlian;
			}
			set
			{
				if ((this._bidang_keahlian != value))
				{
					this.Onbidang_keahlianChanging(value);
					this.SendPropertyChanging();
					this._bidang_keahlian = value;
					this.SendPropertyChanged("bidang_keahlian");
					this.Onbidang_keahlianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(100)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_dosen_tb_proposal", Storage="_tb_proposals", ThisKey="id_dosen", OtherKey="id_pembimbing_1")]
		public EntitySet<tb_proposal> tb_proposals
		{
			get
			{
				return this._tb_proposals;
			}
			set
			{
				this._tb_proposals.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_dosen_tb_proposal1", Storage="_tb_proposals1", ThisKey="id_dosen", OtherKey="id_pembimbing_2")]
		public EntitySet<tb_proposal> tb_proposals1
		{
			get
			{
				return this._tb_proposals1;
			}
			set
			{
				this._tb_proposals1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_dosen_tb_room", Storage="_tb_rooms", ThisKey="id_dosen", OtherKey="id_pembimbing")]
		public EntitySet<tb_room> tb_rooms
		{
			get
			{
				return this._tb_rooms;
			}
			set
			{
				this._tb_rooms.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_fakulta_tb_dosen", Storage="_tb_fakulta", ThisKey="id_fakultas", OtherKey="id_fakultas", IsForeignKey=true)]
		public tb_fakulta tb_fakulta
		{
			get
			{
				return this._tb_fakulta.Entity;
			}
			set
			{
				tb_fakulta previousValue = this._tb_fakulta.Entity;
				if (((previousValue != value) 
							|| (this._tb_fakulta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_fakulta.Entity = null;
						previousValue.tb_dosens.Remove(this);
					}
					this._tb_fakulta.Entity = value;
					if ((value != null))
					{
						value.tb_dosens.Add(this);
						this._id_fakultas = value.id_fakultas;
					}
					else
					{
						this._id_fakultas = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_fakulta");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_jabatan_tb_dosen", Storage="_tb_jabatan", ThisKey="id_jabatan", OtherKey="id_jabatan", IsForeignKey=true)]
		public tb_jabatan tb_jabatan
		{
			get
			{
				return this._tb_jabatan.Entity;
			}
			set
			{
				tb_jabatan previousValue = this._tb_jabatan.Entity;
				if (((previousValue != value) 
							|| (this._tb_jabatan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_jabatan.Entity = null;
						previousValue.tb_dosens.Remove(this);
					}
					this._tb_jabatan.Entity = value;
					if ((value != null))
					{
						value.tb_dosens.Add(this);
						this._id_jabatan = value.id_jabatan;
					}
					else
					{
						this._id_jabatan = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_jabatan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_jurusan_tb_dosen", Storage="_tb_jurusan", ThisKey="id_jurusan", OtherKey="id_jurusan", IsForeignKey=true)]
		public tb_jurusan tb_jurusan
		{
			get
			{
				return this._tb_jurusan.Entity;
			}
			set
			{
				tb_jurusan previousValue = this._tb_jurusan.Entity;
				if (((previousValue != value) 
							|| (this._tb_jurusan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_jurusan.Entity = null;
						previousValue.tb_dosens.Remove(this);
					}
					this._tb_jurusan.Entity = value;
					if ((value != null))
					{
						value.tb_dosens.Add(this);
						this._id_jurusan = value.id_jurusan;
					}
					else
					{
						this._id_jurusan = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_jurusan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_proposals(tb_proposal entity)
		{
			this.SendPropertyChanging();
			entity.tb_dosen = this;
		}
		
		private void detach_tb_proposals(tb_proposal entity)
		{
			this.SendPropertyChanging();
			entity.tb_dosen = null;
		}
		
		private void attach_tb_proposals1(tb_proposal entity)
		{
			this.SendPropertyChanging();
			entity.tb_dosen1 = this;
		}
		
		private void detach_tb_proposals1(tb_proposal entity)
		{
			this.SendPropertyChanging();
			entity.tb_dosen1 = null;
		}
		
		private void attach_tb_rooms(tb_room entity)
		{
			this.SendPropertyChanging();
			entity.tb_dosen = this;
		}
		
		private void detach_tb_rooms(tb_room entity)
		{
			this.SendPropertyChanging();
			entity.tb_dosen = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_fakultas")]
	public partial class tb_fakulta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_fakultas;
		
		private string _nama_fakultas;
		
		private EntitySet<tb_dosen> _tb_dosens;
		
		private EntitySet<tb_mahasiswa> _tb_mahasiswas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_fakultasChanging(int value);
    partial void Onid_fakultasChanged();
    partial void Onnama_fakultasChanging(string value);
    partial void Onnama_fakultasChanged();
    #endregion
		
		public tb_fakulta()
		{
			this._tb_dosens = new EntitySet<tb_dosen>(new Action<tb_dosen>(this.attach_tb_dosens), new Action<tb_dosen>(this.detach_tb_dosens));
			this._tb_mahasiswas = new EntitySet<tb_mahasiswa>(new Action<tb_mahasiswa>(this.attach_tb_mahasiswas), new Action<tb_mahasiswa>(this.detach_tb_mahasiswas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_fakultas", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_fakultas
		{
			get
			{
				return this._id_fakultas;
			}
			set
			{
				if ((this._id_fakultas != value))
				{
					this.Onid_fakultasChanging(value);
					this.SendPropertyChanging();
					this._id_fakultas = value;
					this.SendPropertyChanged("id_fakultas");
					this.Onid_fakultasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_fakultas", DbType="VarChar(50)")]
		public string nama_fakultas
		{
			get
			{
				return this._nama_fakultas;
			}
			set
			{
				if ((this._nama_fakultas != value))
				{
					this.Onnama_fakultasChanging(value);
					this.SendPropertyChanging();
					this._nama_fakultas = value;
					this.SendPropertyChanged("nama_fakultas");
					this.Onnama_fakultasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_fakulta_tb_dosen", Storage="_tb_dosens", ThisKey="id_fakultas", OtherKey="id_fakultas")]
		public EntitySet<tb_dosen> tb_dosens
		{
			get
			{
				return this._tb_dosens;
			}
			set
			{
				this._tb_dosens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_fakulta_tb_mahasiswa", Storage="_tb_mahasiswas", ThisKey="id_fakultas", OtherKey="id_fakultas")]
		public EntitySet<tb_mahasiswa> tb_mahasiswas
		{
			get
			{
				return this._tb_mahasiswas;
			}
			set
			{
				this._tb_mahasiswas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_dosens(tb_dosen entity)
		{
			this.SendPropertyChanging();
			entity.tb_fakulta = this;
		}
		
		private void detach_tb_dosens(tb_dosen entity)
		{
			this.SendPropertyChanging();
			entity.tb_fakulta = null;
		}
		
		private void attach_tb_mahasiswas(tb_mahasiswa entity)
		{
			this.SendPropertyChanging();
			entity.tb_fakulta = this;
		}
		
		private void detach_tb_mahasiswas(tb_mahasiswa entity)
		{
			this.SendPropertyChanging();
			entity.tb_fakulta = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_jabatan")]
	public partial class tb_jabatan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_jabatan;
		
		private string _nama_jabatan;
		
		private EntitySet<tb_dosen> _tb_dosens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_jabatanChanging(int value);
    partial void Onid_jabatanChanged();
    partial void Onnama_jabatanChanging(string value);
    partial void Onnama_jabatanChanged();
    #endregion
		
		public tb_jabatan()
		{
			this._tb_dosens = new EntitySet<tb_dosen>(new Action<tb_dosen>(this.attach_tb_dosens), new Action<tb_dosen>(this.detach_tb_dosens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_jabatan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_jabatan
		{
			get
			{
				return this._id_jabatan;
			}
			set
			{
				if ((this._id_jabatan != value))
				{
					this.Onid_jabatanChanging(value);
					this.SendPropertyChanging();
					this._id_jabatan = value;
					this.SendPropertyChanged("id_jabatan");
					this.Onid_jabatanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_jabatan", DbType="VarChar(50)")]
		public string nama_jabatan
		{
			get
			{
				return this._nama_jabatan;
			}
			set
			{
				if ((this._nama_jabatan != value))
				{
					this.Onnama_jabatanChanging(value);
					this.SendPropertyChanging();
					this._nama_jabatan = value;
					this.SendPropertyChanged("nama_jabatan");
					this.Onnama_jabatanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_jabatan_tb_dosen", Storage="_tb_dosens", ThisKey="id_jabatan", OtherKey="id_jabatan")]
		public EntitySet<tb_dosen> tb_dosens
		{
			get
			{
				return this._tb_dosens;
			}
			set
			{
				this._tb_dosens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_dosens(tb_dosen entity)
		{
			this.SendPropertyChanging();
			entity.tb_jabatan = this;
		}
		
		private void detach_tb_dosens(tb_dosen entity)
		{
			this.SendPropertyChanging();
			entity.tb_jabatan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_jurusan")]
	public partial class tb_jurusan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_jurusan;
		
		private string _nama_jurusan;
		
		private EntitySet<tb_dosen> _tb_dosens;
		
		private EntitySet<tb_mahasiswa> _tb_mahasiswas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_jurusanChanging(int value);
    partial void Onid_jurusanChanged();
    partial void Onnama_jurusanChanging(string value);
    partial void Onnama_jurusanChanged();
    #endregion
		
		public tb_jurusan()
		{
			this._tb_dosens = new EntitySet<tb_dosen>(new Action<tb_dosen>(this.attach_tb_dosens), new Action<tb_dosen>(this.detach_tb_dosens));
			this._tb_mahasiswas = new EntitySet<tb_mahasiswa>(new Action<tb_mahasiswa>(this.attach_tb_mahasiswas), new Action<tb_mahasiswa>(this.detach_tb_mahasiswas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_jurusan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_jurusan
		{
			get
			{
				return this._id_jurusan;
			}
			set
			{
				if ((this._id_jurusan != value))
				{
					this.Onid_jurusanChanging(value);
					this.SendPropertyChanging();
					this._id_jurusan = value;
					this.SendPropertyChanged("id_jurusan");
					this.Onid_jurusanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_jurusan", DbType="VarChar(50)")]
		public string nama_jurusan
		{
			get
			{
				return this._nama_jurusan;
			}
			set
			{
				if ((this._nama_jurusan != value))
				{
					this.Onnama_jurusanChanging(value);
					this.SendPropertyChanging();
					this._nama_jurusan = value;
					this.SendPropertyChanged("nama_jurusan");
					this.Onnama_jurusanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_jurusan_tb_dosen", Storage="_tb_dosens", ThisKey="id_jurusan", OtherKey="id_jurusan")]
		public EntitySet<tb_dosen> tb_dosens
		{
			get
			{
				return this._tb_dosens;
			}
			set
			{
				this._tb_dosens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_jurusan_tb_mahasiswa", Storage="_tb_mahasiswas", ThisKey="id_jurusan", OtherKey="id_jurusan")]
		public EntitySet<tb_mahasiswa> tb_mahasiswas
		{
			get
			{
				return this._tb_mahasiswas;
			}
			set
			{
				this._tb_mahasiswas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_dosens(tb_dosen entity)
		{
			this.SendPropertyChanging();
			entity.tb_jurusan = this;
		}
		
		private void detach_tb_dosens(tb_dosen entity)
		{
			this.SendPropertyChanging();
			entity.tb_jurusan = null;
		}
		
		private void attach_tb_mahasiswas(tb_mahasiswa entity)
		{
			this.SendPropertyChanging();
			entity.tb_jurusan = this;
		}
		
		private void detach_tb_mahasiswas(tb_mahasiswa entity)
		{
			this.SendPropertyChanging();
			entity.tb_jurusan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_kaprodi")]
	public partial class tb_kaprodi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pengguna;
		
		private string _username;
		
		private string _password;
		
		private string _posisi;
		
		private System.Nullable<int> _id_jurusan;
		
		private System.Nullable<int> _id_fakultas;
		
		private string _nama;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_penggunaChanging(int value);
    partial void Onid_penggunaChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnposisiChanging(string value);
    partial void OnposisiChanged();
    partial void Onid_jurusanChanging(System.Nullable<int> value);
    partial void Onid_jurusanChanged();
    partial void Onid_fakultasChanging(System.Nullable<int> value);
    partial void Onid_fakultasChanged();
    partial void OnnamaChanging(string value);
    partial void OnnamaChanged();
    #endregion
		
		public tb_kaprodi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pengguna", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_pengguna
		{
			get
			{
				return this._id_pengguna;
			}
			set
			{
				if ((this._id_pengguna != value))
				{
					this.Onid_penggunaChanging(value);
					this.SendPropertyChanging();
					this._id_pengguna = value;
					this.SendPropertyChanged("id_pengguna");
					this.Onid_penggunaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(100)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_posisi", DbType="VarChar(30)")]
		public string posisi
		{
			get
			{
				return this._posisi;
			}
			set
			{
				if ((this._posisi != value))
				{
					this.OnposisiChanging(value);
					this.SendPropertyChanging();
					this._posisi = value;
					this.SendPropertyChanged("posisi");
					this.OnposisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_jurusan", DbType="Int")]
		public System.Nullable<int> id_jurusan
		{
			get
			{
				return this._id_jurusan;
			}
			set
			{
				if ((this._id_jurusan != value))
				{
					this.Onid_jurusanChanging(value);
					this.SendPropertyChanging();
					this._id_jurusan = value;
					this.SendPropertyChanged("id_jurusan");
					this.Onid_jurusanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_fakultas", DbType="Int")]
		public System.Nullable<int> id_fakultas
		{
			get
			{
				return this._id_fakultas;
			}
			set
			{
				if ((this._id_fakultas != value))
				{
					this.Onid_fakultasChanging(value);
					this.SendPropertyChanging();
					this._id_fakultas = value;
					this.SendPropertyChanged("id_fakultas");
					this.Onid_fakultasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="VarChar(50)")]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this.OnnamaChanging(value);
					this.SendPropertyChanging();
					this._nama = value;
					this.SendPropertyChanged("nama");
					this.OnnamaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_mahasiswa")]
	public partial class tb_mahasiswa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_mahasiswa;
		
		private string _nim;
		
		private string _nama;
		
		private System.Nullable<int> _id_jurusan;
		
		private System.Nullable<int> _id_fakultas;
		
		private System.Nullable<double> _ipk;
		
		private string _alamat;
		
		private string _telp;
		
		private string _password;
		
		private EntitySet<tb_proposal> _tb_proposals;
		
		private EntitySet<tb_room> _tb_rooms;
		
		private EntityRef<tb_fakulta> _tb_fakulta;
		
		private EntityRef<tb_jurusan> _tb_jurusan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_mahasiswaChanging(int value);
    partial void Onid_mahasiswaChanged();
    partial void OnnimChanging(string value);
    partial void OnnimChanged();
    partial void OnnamaChanging(string value);
    partial void OnnamaChanged();
    partial void Onid_jurusanChanging(System.Nullable<int> value);
    partial void Onid_jurusanChanged();
    partial void Onid_fakultasChanging(System.Nullable<int> value);
    partial void Onid_fakultasChanged();
    partial void OnipkChanging(System.Nullable<double> value);
    partial void OnipkChanged();
    partial void OnalamatChanging(string value);
    partial void OnalamatChanged();
    partial void OntelpChanging(string value);
    partial void OntelpChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
		
		public tb_mahasiswa()
		{
			this._tb_proposals = new EntitySet<tb_proposal>(new Action<tb_proposal>(this.attach_tb_proposals), new Action<tb_proposal>(this.detach_tb_proposals));
			this._tb_rooms = new EntitySet<tb_room>(new Action<tb_room>(this.attach_tb_rooms), new Action<tb_room>(this.detach_tb_rooms));
			this._tb_fakulta = default(EntityRef<tb_fakulta>);
			this._tb_jurusan = default(EntityRef<tb_jurusan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_mahasiswa", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_mahasiswa
		{
			get
			{
				return this._id_mahasiswa;
			}
			set
			{
				if ((this._id_mahasiswa != value))
				{
					this.Onid_mahasiswaChanging(value);
					this.SendPropertyChanging();
					this._id_mahasiswa = value;
					this.SendPropertyChanged("id_mahasiswa");
					this.Onid_mahasiswaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nim", DbType="VarChar(20)")]
		public string nim
		{
			get
			{
				return this._nim;
			}
			set
			{
				if ((this._nim != value))
				{
					this.OnnimChanging(value);
					this.SendPropertyChanging();
					this._nim = value;
					this.SendPropertyChanged("nim");
					this.OnnimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="VarChar(50)")]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this.OnnamaChanging(value);
					this.SendPropertyChanging();
					this._nama = value;
					this.SendPropertyChanged("nama");
					this.OnnamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_jurusan", DbType="Int")]
		public System.Nullable<int> id_jurusan
		{
			get
			{
				return this._id_jurusan;
			}
			set
			{
				if ((this._id_jurusan != value))
				{
					if (this._tb_jurusan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_jurusanChanging(value);
					this.SendPropertyChanging();
					this._id_jurusan = value;
					this.SendPropertyChanged("id_jurusan");
					this.Onid_jurusanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_fakultas", DbType="Int")]
		public System.Nullable<int> id_fakultas
		{
			get
			{
				return this._id_fakultas;
			}
			set
			{
				if ((this._id_fakultas != value))
				{
					if (this._tb_fakulta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_fakultasChanging(value);
					this.SendPropertyChanging();
					this._id_fakultas = value;
					this.SendPropertyChanged("id_fakultas");
					this.Onid_fakultasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ipk", DbType="Float")]
		public System.Nullable<double> ipk
		{
			get
			{
				return this._ipk;
			}
			set
			{
				if ((this._ipk != value))
				{
					this.OnipkChanging(value);
					this.SendPropertyChanging();
					this._ipk = value;
					this.SendPropertyChanged("ipk");
					this.OnipkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alamat", DbType="VarChar(255)")]
		public string alamat
		{
			get
			{
				return this._alamat;
			}
			set
			{
				if ((this._alamat != value))
				{
					this.OnalamatChanging(value);
					this.SendPropertyChanging();
					this._alamat = value;
					this.SendPropertyChanged("alamat");
					this.OnalamatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telp", DbType="VarChar(20)")]
		public string telp
		{
			get
			{
				return this._telp;
			}
			set
			{
				if ((this._telp != value))
				{
					this.OntelpChanging(value);
					this.SendPropertyChanging();
					this._telp = value;
					this.SendPropertyChanged("telp");
					this.OntelpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(100)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_mahasiswa_tb_proposal", Storage="_tb_proposals", ThisKey="id_mahasiswa", OtherKey="id_mahasiswa")]
		public EntitySet<tb_proposal> tb_proposals
		{
			get
			{
				return this._tb_proposals;
			}
			set
			{
				this._tb_proposals.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_mahasiswa_tb_room", Storage="_tb_rooms", ThisKey="id_mahasiswa", OtherKey="id_mahasiswa")]
		public EntitySet<tb_room> tb_rooms
		{
			get
			{
				return this._tb_rooms;
			}
			set
			{
				this._tb_rooms.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_fakulta_tb_mahasiswa", Storage="_tb_fakulta", ThisKey="id_fakultas", OtherKey="id_fakultas", IsForeignKey=true)]
		public tb_fakulta tb_fakulta
		{
			get
			{
				return this._tb_fakulta.Entity;
			}
			set
			{
				tb_fakulta previousValue = this._tb_fakulta.Entity;
				if (((previousValue != value) 
							|| (this._tb_fakulta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_fakulta.Entity = null;
						previousValue.tb_mahasiswas.Remove(this);
					}
					this._tb_fakulta.Entity = value;
					if ((value != null))
					{
						value.tb_mahasiswas.Add(this);
						this._id_fakultas = value.id_fakultas;
					}
					else
					{
						this._id_fakultas = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_fakulta");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_jurusan_tb_mahasiswa", Storage="_tb_jurusan", ThisKey="id_jurusan", OtherKey="id_jurusan", IsForeignKey=true)]
		public tb_jurusan tb_jurusan
		{
			get
			{
				return this._tb_jurusan.Entity;
			}
			set
			{
				tb_jurusan previousValue = this._tb_jurusan.Entity;
				if (((previousValue != value) 
							|| (this._tb_jurusan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_jurusan.Entity = null;
						previousValue.tb_mahasiswas.Remove(this);
					}
					this._tb_jurusan.Entity = value;
					if ((value != null))
					{
						value.tb_mahasiswas.Add(this);
						this._id_jurusan = value.id_jurusan;
					}
					else
					{
						this._id_jurusan = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_jurusan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_proposals(tb_proposal entity)
		{
			this.SendPropertyChanging();
			entity.tb_mahasiswa = this;
		}
		
		private void detach_tb_proposals(tb_proposal entity)
		{
			this.SendPropertyChanging();
			entity.tb_mahasiswa = null;
		}
		
		private void attach_tb_rooms(tb_room entity)
		{
			this.SendPropertyChanging();
			entity.tb_mahasiswa = this;
		}
		
		private void detach_tb_rooms(tb_room entity)
		{
			this.SendPropertyChanging();
			entity.tb_mahasiswa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_peminatan")]
	public partial class tb_peminatan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_peminatan;
		
		private string _nama_peminatan;
		
		private System.Nullable<int> _id_fakultas;
		
		private System.Nullable<int> _id_jurusan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_peminatanChanging(int value);
    partial void Onid_peminatanChanged();
    partial void Onnama_peminatanChanging(string value);
    partial void Onnama_peminatanChanged();
    partial void Onid_fakultasChanging(System.Nullable<int> value);
    partial void Onid_fakultasChanged();
    partial void Onid_jurusanChanging(System.Nullable<int> value);
    partial void Onid_jurusanChanged();
    #endregion
		
		public tb_peminatan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_peminatan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_peminatan
		{
			get
			{
				return this._id_peminatan;
			}
			set
			{
				if ((this._id_peminatan != value))
				{
					this.Onid_peminatanChanging(value);
					this.SendPropertyChanging();
					this._id_peminatan = value;
					this.SendPropertyChanged("id_peminatan");
					this.Onid_peminatanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_peminatan", DbType="VarChar(50)")]
		public string nama_peminatan
		{
			get
			{
				return this._nama_peminatan;
			}
			set
			{
				if ((this._nama_peminatan != value))
				{
					this.Onnama_peminatanChanging(value);
					this.SendPropertyChanging();
					this._nama_peminatan = value;
					this.SendPropertyChanged("nama_peminatan");
					this.Onnama_peminatanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_fakultas", DbType="Int")]
		public System.Nullable<int> id_fakultas
		{
			get
			{
				return this._id_fakultas;
			}
			set
			{
				if ((this._id_fakultas != value))
				{
					this.Onid_fakultasChanging(value);
					this.SendPropertyChanging();
					this._id_fakultas = value;
					this.SendPropertyChanged("id_fakultas");
					this.Onid_fakultasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_jurusan", DbType="Int")]
		public System.Nullable<int> id_jurusan
		{
			get
			{
				return this._id_jurusan;
			}
			set
			{
				if ((this._id_jurusan != value))
				{
					this.Onid_jurusanChanging(value);
					this.SendPropertyChanging();
					this._id_jurusan = value;
					this.SendPropertyChanged("id_jurusan");
					this.Onid_jurusanChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_proposal")]
	public partial class tb_proposal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_proposal;
		
		private System.Nullable<int> _id_mahasiswa;
		
		private System.Nullable<System.DateTime> _tgl_submit;
		
		private string _judul_skripsi;
		
		private System.Nullable<int> _id_pembimbing_1;
		
		private System.Nullable<int> _id_pembimbing_2;
		
		private string _status_proposal;
		
		private string _catatan_kaprodi;
		
		private System.Nullable<int> _id_kaprodi;
		
		private System.Nullable<int> _id_peminatan;
		
		private System.Nullable<int> _id_thn_akademik;
		
		private EntityRef<tb_dosen> _tb_dosen;
		
		private EntityRef<tb_dosen> _tb_dosen1;
		
		private EntityRef<tb_mahasiswa> _tb_mahasiswa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_proposalChanging(int value);
    partial void Onid_proposalChanged();
    partial void Onid_mahasiswaChanging(System.Nullable<int> value);
    partial void Onid_mahasiswaChanged();
    partial void Ontgl_submitChanging(System.Nullable<System.DateTime> value);
    partial void Ontgl_submitChanged();
    partial void Onjudul_skripsiChanging(string value);
    partial void Onjudul_skripsiChanged();
    partial void Onid_pembimbing_1Changing(System.Nullable<int> value);
    partial void Onid_pembimbing_1Changed();
    partial void Onid_pembimbing_2Changing(System.Nullable<int> value);
    partial void Onid_pembimbing_2Changed();
    partial void Onstatus_proposalChanging(string value);
    partial void Onstatus_proposalChanged();
    partial void Oncatatan_kaprodiChanging(string value);
    partial void Oncatatan_kaprodiChanged();
    partial void Onid_kaprodiChanging(System.Nullable<int> value);
    partial void Onid_kaprodiChanged();
    partial void Onid_peminatanChanging(System.Nullable<int> value);
    partial void Onid_peminatanChanged();
    partial void Onid_thn_akademikChanging(System.Nullable<int> value);
    partial void Onid_thn_akademikChanged();
    #endregion
		
		public tb_proposal()
		{
			this._tb_dosen = default(EntityRef<tb_dosen>);
			this._tb_dosen1 = default(EntityRef<tb_dosen>);
			this._tb_mahasiswa = default(EntityRef<tb_mahasiswa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_proposal", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_proposal
		{
			get
			{
				return this._id_proposal;
			}
			set
			{
				if ((this._id_proposal != value))
				{
					this.Onid_proposalChanging(value);
					this.SendPropertyChanging();
					this._id_proposal = value;
					this.SendPropertyChanged("id_proposal");
					this.Onid_proposalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_mahasiswa", DbType="Int")]
		public System.Nullable<int> id_mahasiswa
		{
			get
			{
				return this._id_mahasiswa;
			}
			set
			{
				if ((this._id_mahasiswa != value))
				{
					if (this._tb_mahasiswa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_mahasiswaChanging(value);
					this.SendPropertyChanging();
					this._id_mahasiswa = value;
					this.SendPropertyChanged("id_mahasiswa");
					this.Onid_mahasiswaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgl_submit", DbType="Date")]
		public System.Nullable<System.DateTime> tgl_submit
		{
			get
			{
				return this._tgl_submit;
			}
			set
			{
				if ((this._tgl_submit != value))
				{
					this.Ontgl_submitChanging(value);
					this.SendPropertyChanging();
					this._tgl_submit = value;
					this.SendPropertyChanged("tgl_submit");
					this.Ontgl_submitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_judul_skripsi", DbType="VarChar(100)")]
		public string judul_skripsi
		{
			get
			{
				return this._judul_skripsi;
			}
			set
			{
				if ((this._judul_skripsi != value))
				{
					this.Onjudul_skripsiChanging(value);
					this.SendPropertyChanging();
					this._judul_skripsi = value;
					this.SendPropertyChanged("judul_skripsi");
					this.Onjudul_skripsiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pembimbing_1", DbType="Int")]
		public System.Nullable<int> id_pembimbing_1
		{
			get
			{
				return this._id_pembimbing_1;
			}
			set
			{
				if ((this._id_pembimbing_1 != value))
				{
					if (this._tb_dosen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_pembimbing_1Changing(value);
					this.SendPropertyChanging();
					this._id_pembimbing_1 = value;
					this.SendPropertyChanged("id_pembimbing_1");
					this.Onid_pembimbing_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pembimbing_2", DbType="Int")]
		public System.Nullable<int> id_pembimbing_2
		{
			get
			{
				return this._id_pembimbing_2;
			}
			set
			{
				if ((this._id_pembimbing_2 != value))
				{
					if (this._tb_dosen1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_pembimbing_2Changing(value);
					this.SendPropertyChanging();
					this._id_pembimbing_2 = value;
					this.SendPropertyChanged("id_pembimbing_2");
					this.Onid_pembimbing_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_proposal", DbType="VarChar(100)")]
		public string status_proposal
		{
			get
			{
				return this._status_proposal;
			}
			set
			{
				if ((this._status_proposal != value))
				{
					this.Onstatus_proposalChanging(value);
					this.SendPropertyChanging();
					this._status_proposal = value;
					this.SendPropertyChanged("status_proposal");
					this.Onstatus_proposalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_catatan_kaprodi", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string catatan_kaprodi
		{
			get
			{
				return this._catatan_kaprodi;
			}
			set
			{
				if ((this._catatan_kaprodi != value))
				{
					this.Oncatatan_kaprodiChanging(value);
					this.SendPropertyChanging();
					this._catatan_kaprodi = value;
					this.SendPropertyChanged("catatan_kaprodi");
					this.Oncatatan_kaprodiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_kaprodi", DbType="Int")]
		public System.Nullable<int> id_kaprodi
		{
			get
			{
				return this._id_kaprodi;
			}
			set
			{
				if ((this._id_kaprodi != value))
				{
					this.Onid_kaprodiChanging(value);
					this.SendPropertyChanging();
					this._id_kaprodi = value;
					this.SendPropertyChanged("id_kaprodi");
					this.Onid_kaprodiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_peminatan", DbType="Int")]
		public System.Nullable<int> id_peminatan
		{
			get
			{
				return this._id_peminatan;
			}
			set
			{
				if ((this._id_peminatan != value))
				{
					this.Onid_peminatanChanging(value);
					this.SendPropertyChanging();
					this._id_peminatan = value;
					this.SendPropertyChanged("id_peminatan");
					this.Onid_peminatanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_thn_akademik", DbType="Int")]
		public System.Nullable<int> id_thn_akademik
		{
			get
			{
				return this._id_thn_akademik;
			}
			set
			{
				if ((this._id_thn_akademik != value))
				{
					this.Onid_thn_akademikChanging(value);
					this.SendPropertyChanging();
					this._id_thn_akademik = value;
					this.SendPropertyChanged("id_thn_akademik");
					this.Onid_thn_akademikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_dosen_tb_proposal", Storage="_tb_dosen", ThisKey="id_pembimbing_1", OtherKey="id_dosen", IsForeignKey=true)]
		public tb_dosen tb_dosen
		{
			get
			{
				return this._tb_dosen.Entity;
			}
			set
			{
				tb_dosen previousValue = this._tb_dosen.Entity;
				if (((previousValue != value) 
							|| (this._tb_dosen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_dosen.Entity = null;
						previousValue.tb_proposals.Remove(this);
					}
					this._tb_dosen.Entity = value;
					if ((value != null))
					{
						value.tb_proposals.Add(this);
						this._id_pembimbing_1 = value.id_dosen;
					}
					else
					{
						this._id_pembimbing_1 = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_dosen");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_dosen_tb_proposal1", Storage="_tb_dosen1", ThisKey="id_pembimbing_2", OtherKey="id_dosen", IsForeignKey=true)]
		public tb_dosen tb_dosen1
		{
			get
			{
				return this._tb_dosen1.Entity;
			}
			set
			{
				tb_dosen previousValue = this._tb_dosen1.Entity;
				if (((previousValue != value) 
							|| (this._tb_dosen1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_dosen1.Entity = null;
						previousValue.tb_proposals1.Remove(this);
					}
					this._tb_dosen1.Entity = value;
					if ((value != null))
					{
						value.tb_proposals1.Add(this);
						this._id_pembimbing_2 = value.id_dosen;
					}
					else
					{
						this._id_pembimbing_2 = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_dosen1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_mahasiswa_tb_proposal", Storage="_tb_mahasiswa", ThisKey="id_mahasiswa", OtherKey="id_mahasiswa", IsForeignKey=true)]
		public tb_mahasiswa tb_mahasiswa
		{
			get
			{
				return this._tb_mahasiswa.Entity;
			}
			set
			{
				tb_mahasiswa previousValue = this._tb_mahasiswa.Entity;
				if (((previousValue != value) 
							|| (this._tb_mahasiswa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_mahasiswa.Entity = null;
						previousValue.tb_proposals.Remove(this);
					}
					this._tb_mahasiswa.Entity = value;
					if ((value != null))
					{
						value.tb_proposals.Add(this);
						this._id_mahasiswa = value.id_mahasiswa;
					}
					else
					{
						this._id_mahasiswa = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_mahasiswa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_room")]
	public partial class tb_room : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_room;
		
		private System.Nullable<int> _id_mahasiswa;
		
		private System.Nullable<int> _id_pembimbing;
		
		private System.Nullable<System.DateTime> _tgl_room;
		
		private System.Nullable<int> _id_proposal;
		
		private EntitySet<tb_bimbingan> _tb_bimbingans;
		
		private EntitySet<tb_chat> _tb_chats;
		
		private EntityRef<tb_dosen> _tb_dosen;
		
		private EntityRef<tb_mahasiswa> _tb_mahasiswa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_roomChanging(int value);
    partial void Onid_roomChanged();
    partial void Onid_mahasiswaChanging(System.Nullable<int> value);
    partial void Onid_mahasiswaChanged();
    partial void Onid_pembimbingChanging(System.Nullable<int> value);
    partial void Onid_pembimbingChanged();
    partial void Ontgl_roomChanging(System.Nullable<System.DateTime> value);
    partial void Ontgl_roomChanged();
    partial void Onid_proposalChanging(System.Nullable<int> value);
    partial void Onid_proposalChanged();
    #endregion
		
		public tb_room()
		{
			this._tb_bimbingans = new EntitySet<tb_bimbingan>(new Action<tb_bimbingan>(this.attach_tb_bimbingans), new Action<tb_bimbingan>(this.detach_tb_bimbingans));
			this._tb_chats = new EntitySet<tb_chat>(new Action<tb_chat>(this.attach_tb_chats), new Action<tb_chat>(this.detach_tb_chats));
			this._tb_dosen = default(EntityRef<tb_dosen>);
			this._tb_mahasiswa = default(EntityRef<tb_mahasiswa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_room", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_room
		{
			get
			{
				return this._id_room;
			}
			set
			{
				if ((this._id_room != value))
				{
					this.Onid_roomChanging(value);
					this.SendPropertyChanging();
					this._id_room = value;
					this.SendPropertyChanged("id_room");
					this.Onid_roomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_mahasiswa", DbType="Int")]
		public System.Nullable<int> id_mahasiswa
		{
			get
			{
				return this._id_mahasiswa;
			}
			set
			{
				if ((this._id_mahasiswa != value))
				{
					if (this._tb_mahasiswa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_mahasiswaChanging(value);
					this.SendPropertyChanging();
					this._id_mahasiswa = value;
					this.SendPropertyChanged("id_mahasiswa");
					this.Onid_mahasiswaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pembimbing", DbType="Int")]
		public System.Nullable<int> id_pembimbing
		{
			get
			{
				return this._id_pembimbing;
			}
			set
			{
				if ((this._id_pembimbing != value))
				{
					if (this._tb_dosen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_pembimbingChanging(value);
					this.SendPropertyChanging();
					this._id_pembimbing = value;
					this.SendPropertyChanged("id_pembimbing");
					this.Onid_pembimbingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tgl_room", DbType="DateTime")]
		public System.Nullable<System.DateTime> tgl_room
		{
			get
			{
				return this._tgl_room;
			}
			set
			{
				if ((this._tgl_room != value))
				{
					this.Ontgl_roomChanging(value);
					this.SendPropertyChanging();
					this._tgl_room = value;
					this.SendPropertyChanged("tgl_room");
					this.Ontgl_roomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_proposal", DbType="Int")]
		public System.Nullable<int> id_proposal
		{
			get
			{
				return this._id_proposal;
			}
			set
			{
				if ((this._id_proposal != value))
				{
					this.Onid_proposalChanging(value);
					this.SendPropertyChanging();
					this._id_proposal = value;
					this.SendPropertyChanged("id_proposal");
					this.Onid_proposalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_room_tb_bimbingan", Storage="_tb_bimbingans", ThisKey="id_room", OtherKey="id_room")]
		public EntitySet<tb_bimbingan> tb_bimbingans
		{
			get
			{
				return this._tb_bimbingans;
			}
			set
			{
				this._tb_bimbingans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_room_tb_chat", Storage="_tb_chats", ThisKey="id_room", OtherKey="id_room")]
		public EntitySet<tb_chat> tb_chats
		{
			get
			{
				return this._tb_chats;
			}
			set
			{
				this._tb_chats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_dosen_tb_room", Storage="_tb_dosen", ThisKey="id_pembimbing", OtherKey="id_dosen", IsForeignKey=true)]
		public tb_dosen tb_dosen
		{
			get
			{
				return this._tb_dosen.Entity;
			}
			set
			{
				tb_dosen previousValue = this._tb_dosen.Entity;
				if (((previousValue != value) 
							|| (this._tb_dosen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_dosen.Entity = null;
						previousValue.tb_rooms.Remove(this);
					}
					this._tb_dosen.Entity = value;
					if ((value != null))
					{
						value.tb_rooms.Add(this);
						this._id_pembimbing = value.id_dosen;
					}
					else
					{
						this._id_pembimbing = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_dosen");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_mahasiswa_tb_room", Storage="_tb_mahasiswa", ThisKey="id_mahasiswa", OtherKey="id_mahasiswa", IsForeignKey=true)]
		public tb_mahasiswa tb_mahasiswa
		{
			get
			{
				return this._tb_mahasiswa.Entity;
			}
			set
			{
				tb_mahasiswa previousValue = this._tb_mahasiswa.Entity;
				if (((previousValue != value) 
							|| (this._tb_mahasiswa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_mahasiswa.Entity = null;
						previousValue.tb_rooms.Remove(this);
					}
					this._tb_mahasiswa.Entity = value;
					if ((value != null))
					{
						value.tb_rooms.Add(this);
						this._id_mahasiswa = value.id_mahasiswa;
					}
					else
					{
						this._id_mahasiswa = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_mahasiswa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_bimbingans(tb_bimbingan entity)
		{
			this.SendPropertyChanging();
			entity.tb_room = this;
		}
		
		private void detach_tb_bimbingans(tb_bimbingan entity)
		{
			this.SendPropertyChanging();
			entity.tb_room = null;
		}
		
		private void attach_tb_chats(tb_chat entity)
		{
			this.SendPropertyChanging();
			entity.tb_room = this;
		}
		
		private void detach_tb_chats(tb_chat entity)
		{
			this.SendPropertyChanging();
			entity.tb_room = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_chat")]
	public partial class tb_chat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_chat;
		
		private System.Nullable<int> _id_room;
		
		private System.Nullable<int> _id_sender;
		
		private System.Nullable<int> _id_recipient;
		
		private string _isi;
		
		private System.Nullable<int> _status;
		
		private System.Nullable<System.DateTime> _tanggal_chat;
		
		private EntityRef<tb_room> _tb_room;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_chatChanging(int value);
    partial void Onid_chatChanged();
    partial void Onid_roomChanging(System.Nullable<int> value);
    partial void Onid_roomChanged();
    partial void Onid_senderChanging(System.Nullable<int> value);
    partial void Onid_senderChanged();
    partial void Onid_recipientChanging(System.Nullable<int> value);
    partial void Onid_recipientChanged();
    partial void OnisiChanging(string value);
    partial void OnisiChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void Ontanggal_chatChanging(System.Nullable<System.DateTime> value);
    partial void Ontanggal_chatChanged();
    #endregion
		
		public tb_chat()
		{
			this._tb_room = default(EntityRef<tb_room>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_chat", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_chat
		{
			get
			{
				return this._id_chat;
			}
			set
			{
				if ((this._id_chat != value))
				{
					this.Onid_chatChanging(value);
					this.SendPropertyChanging();
					this._id_chat = value;
					this.SendPropertyChanged("id_chat");
					this.Onid_chatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_room", DbType="Int")]
		public System.Nullable<int> id_room
		{
			get
			{
				return this._id_room;
			}
			set
			{
				if ((this._id_room != value))
				{
					if (this._tb_room.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_roomChanging(value);
					this.SendPropertyChanging();
					this._id_room = value;
					this.SendPropertyChanged("id_room");
					this.Onid_roomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_sender", DbType="Int")]
		public System.Nullable<int> id_sender
		{
			get
			{
				return this._id_sender;
			}
			set
			{
				if ((this._id_sender != value))
				{
					this.Onid_senderChanging(value);
					this.SendPropertyChanging();
					this._id_sender = value;
					this.SendPropertyChanged("id_sender");
					this.Onid_senderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_recipient", DbType="Int")]
		public System.Nullable<int> id_recipient
		{
			get
			{
				return this._id_recipient;
			}
			set
			{
				if ((this._id_recipient != value))
				{
					this.Onid_recipientChanging(value);
					this.SendPropertyChanging();
					this._id_recipient = value;
					this.SendPropertyChanged("id_recipient");
					this.Onid_recipientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isi", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string isi
		{
			get
			{
				return this._isi;
			}
			set
			{
				if ((this._isi != value))
				{
					this.OnisiChanging(value);
					this.SendPropertyChanging();
					this._isi = value;
					this.SendPropertyChanged("isi");
					this.OnisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
		public System.Nullable<int> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggal_chat", DbType="DateTime")]
		public System.Nullable<System.DateTime> tanggal_chat
		{
			get
			{
				return this._tanggal_chat;
			}
			set
			{
				if ((this._tanggal_chat != value))
				{
					this.Ontanggal_chatChanging(value);
					this.SendPropertyChanging();
					this._tanggal_chat = value;
					this.SendPropertyChanged("tanggal_chat");
					this.Ontanggal_chatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_room_tb_chat", Storage="_tb_room", ThisKey="id_room", OtherKey="id_room", IsForeignKey=true)]
		public tb_room tb_room
		{
			get
			{
				return this._tb_room.Entity;
			}
			set
			{
				tb_room previousValue = this._tb_room.Entity;
				if (((previousValue != value) 
							|| (this._tb_room.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_room.Entity = null;
						previousValue.tb_chats.Remove(this);
					}
					this._tb_room.Entity = value;
					if ((value != null))
					{
						value.tb_chats.Add(this);
						this._id_room = value.id_room;
					}
					else
					{
						this._id_room = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_room");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
